### ISSUE TITLE
License needs to be clarified

### ISSUE THREAD

**Issue by stof** [goetas-webservices/soap-server#3]
The readme says this project is under the MIT license. But there is no LICENSE file in the project and the composer.json does not contain the licensing metadata either.

**Comment by stof** [comment]
Side note: I'm not using that project (and I'm not planning to use SOAP anytime soon). I discovered this package as part of a discussion in the Symfony Slack.

**Comment by goetas** [comment]
https://github.com/goetas-webservices/soap-server/commit/a73bd11228425ddb0e32f07f748a4c28b511380c

**Comment by stof** [comment]
you should probably also update the composer.json so that packagist does not show it as an unknown license

**Comment by goetas** [comment]
thanks for the advice, done in https://github.com/goetas-webservices/soap-server/commit/cf50df66ef9c09b7519904b0bbde01cdd51f3699
